/*
 * generated by Xtext 2.10.0
 */
package com.fastpilot.jaus.cjsidl.tests

import com.fastpilot.jaus.cjsidl.jaus.Jaus
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(JausInjectorProvider)
class JausParsingTest{

	@Inject
	ParseHelper<Jaus> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
